### ISSUE TITLE
npm install puts incorrect function name in .bashrc

### ISSUE THREAD

**Issue by yila** [lyze/posh-git-sh#16]
I couldn't find a place to open an issue on the npm site, so I'm opening one here.

When I install posh-git-sh on my mac using npm ("sudo npm install -g posh-git" followed by "posh-git-install" for local user), the installation puts in the following lines:

source ~/posh-git.sh
PROMPT_COMMAND='__git_ps1 "\u@\h: \w" "\\\$ ":'$PROMPT_COMMAND

And I get the following error:
-bash: __git_ps1: command not found

The issue is that posh-git.sh does NOT have a function by that name.  Instead, it is called __posh_git_ps1(){...}.  I've updated my .bashrc to call the right function, but it would be nice if it is corrected in the npm install.

Thanks,

Yasir

**Comment by lyze** [comment]
You'll have to open an issue over at https://github.com/leonardiwagner/npm-posh-git, which is the repository of that script when listed on the NPM site.

Thanks for using the script though!
