### ISSUE TITLE
Terminal issue: lines that wrap in (or near) colour changing statements do not wrap to the next line

### ISSUE THREAD

**Issue by erikhuizinga** [lyze/posh-git-sh#18]
I have a problem when the prompt string is a few characters longer than the window width and a branch name is displayed.

The screenshot below illustrates the issue.
![schermafbeelding 2016-12-02 om 14 09 38](https://cloud.githubusercontent.com/assets/19374736/20835155/55176d14-b899-11e6-9614-92db0f6d6096.png)
What you can see is the branch name is displayed, then the three stacked lines, but then the closing square bracket `]` is shown in blue (instead of yellow) near the beginning of the first line. Also, the input cursor is shown close after the closing square bracket and dollar sign: `] $ |`. The yellow pipe `|` is my cursor, yellow is the intended colour by the way. Also, the working directory is intended that way, it's there so the dir is quite long. Instead, I could have chosen a very long branch name for similar results.

In my `~/.bash_profile` I have set the following.
````bash
export PROMPT_COMMAND='__posh_git_ps1 "$prefix" "$suffix";'$PROMPT_COMMAND
````
where `$prefix` is my `username@hostname workingdir` and `$suffix` is ` $`, both with some colour specification, but nothing more.

When the Terminal window is a little smaller, the problem does not occur; see screenshot below for a terminal window of 77 characters wide. The one above is 80 characters wide. The problem occurs when the windows is 78, 79 or 80 characters wide. Narrower or wider windows behave correctly.
![schermafbeelding 2016-12-02 om 14 21 23](https://cloud.githubusercontent.com/assets/19374736/20835390/9f071ac2-b89a-11e6-80ef-2c600d11d20e.png)
For very narrow Terminal windows (or very long working directories) the problems become worse, especially when the prompt string should wrap around more than 2 lines. Try resizing the Terminal window in a similar situation as my current screenshots show, with quite a long working directory.

**Comment by lyze** [comment]
I am unable to reproduce this. My strong suspicion is that you have not wrapped your color codes in `\[` and `\]` for bash (or `%{` and `%}` for zsh). [This Stackoverflow post has a well-written explanation of this problem.](http://unix.stackexchange.com/questions/105958/terminal-prompt-not-wrapping-correctly) Could you please paste the exact mumbo jumbo used to set `PROMPT_COMMAND`?

**Comment by erikhuizinga** [comment]
Here's the exact code.

```
export PROMPT_COMMAND='__posh_git_ps1 "\[\e[00;37m\]\u@💻  \[\e[00;31m\]\w" "\[\e[00;37m\] \$ \[\e[00m\]";'$PROMPT_COMMAND
```

I know bash does not know the number of printable and unprintable characters, so those should be grouped in `\[` and `\]`. I guess the grouping I currently have is correct, but if you spot any error I'd like to know!

I figured it could be caused by some quirk concerning the laptop emoji 💻 I use. Because it prints in a different font (because my monospaced console font, Source Code Pro, does not support it) it is wider than the terminal font and requires two spaces after the character. However, I tried replacing it with `\h` and the results did not change.
<img width="762" alt="schermafbeelding 2016-12-04 om 11 01 06" src="https://cloud.githubusercontent.com/assets/19374736/20865415/3beb2e38-ba11-11e6-81f5-1c127741b6b9.png">
I conclude that a line breaking in the middle of the posh git string may cause the incorrect wrapping problem.

**Comment by lyze** [comment]
After a little bit of poking around, it just seems that the particular emoji doesn't play nicely at all with the terminal. I opened up a boring terminal prompt, pasted it in. It caused havoc to my prompt if I tried to edit the line and if it was a long line. This feels like a limitation in bash or the terminal emulator. Can check that taking out the emoji eliminates the problem?

**Comment by erikhuizinga** [comment]
@lyze As I said in my previous comment: I can reproduce the problem without the emoji, so the issue isn't caused by it.

**Comment by lyze** [comment]
I can't reproduce the problem when using `\h` on my own computer. (Caveat: It wasn't on a Mac, and I don't have a Mac handy to test.)

The actual expansion of `PS1`:
```
\[\e[00;37m\]\u@\h \[\e[00;31m\]\w\[\e[1;33m\] [\[\e[1;36m\]master ≡\[\e[0;31m\] +1 ~0 -0\[\e[1;33m\]]\[\e[m\]\[\e[00;37m\] $ \[\e[00m\]
```
I can't see anything wrong with it.

I'm really scratching my head here. Some theories that I would need you to help investigate:

* Is there anything else in `$PROMPT_COMMAND` that might mess with `$PS1`?
* Have you tried setting `shopt -s checkwinsize`?
* Try messing with the terminal emulation settings? I think it's "Preferences > Advanced > Emulation".
* Try using `tput` instead of ANSI colors.

**Comment by erikhuizinga** [comment]
Great ideas! Here are my results. (spoiler: no luck...)

* Yes, my `$PROMPT_COMMAND` contains (before prepending my posh Git string): `update_terminal_cwd`. Removing it does not change the issue.
* It was already set and explicitly setting it does not change the issue.
* How do I do this? Is it under Prefs > Advanced > Terminfo (where it says xterm-256color by default)? I tried about 5 different values there and it does not change the issue.
* Currently, my `$PROMPT_COMMAND` implementation is:

```
red=$(tput setaf 1)
gray=$(tput setaf 8)
reset=$(tput sgr0)
export PROMPT_COMMAND='__posh_git_ps1 "\[$gray\]\u@\h \[$red\]\w" "\[$gray\] \$ \[$reset\]";'$PROMPT_COMMAND
```
The issue persist, unfortunately.

Even when using `export PROMPT_COMMAND='__posh_git_ps1 "\u@\h \w" " \$ ";'$PROMPT_COMMAND` or `export PROMPT_COMMAND='__posh_git_ps1 "foo bar" " baz qux ";'$PROMPT_COMMAND` does not change the issue.

**Comment by lyze** [comment]
If you clear `PROMPT_COMMAND` and only set `PS1`, does the problem still occur?
```
PROMPT_COMMAND=
PS1=\[\e[00;37m\]\u@\h \[\e[00;31m\]\w\[\e[1;33m\] [\[\e[1;36m\]master ≡\[\e[1;33m\]]\[\e[m\]\[\e[00;37m\] $ \[\e[00m\]
```

**Comment by erikhuizinga** [comment]
Using
```
PROMPT_COMMAND=
PS1='\[\e[00;37m\]\u@\h \[\e[00;31m\]\w\[\e[1;33m\] [\[\e[1;36m\]master ≡\[\e[1;33m\]]\[\e[m\]\[\e[00;37m\] $ \[\e[00m\]'
```
(i.e. what you said, but with 'quotes')
the results are the same. Something is wrong in the way Terminal wraps a line with grouping of non-printable characters. I think the line break it should insert ends up erroneously within the unprintable group, so it gets ignored somehow.

I guess this rules out posh-git-sh as the culprit, don't you agree? Where do I go next with this issue? The current behaviour is ok if the Terminal window does not have the problematic width (which is one of two or three widths depending on the length of `$PS1` when it prints).

I guess I'll have to resort to a [Terminal alternative](http://alternativeto.net/software/terminal/?platform=mac).

**Comment by lyze** [comment]
I'm out of ideas at the moment. By now, I, too, am fairly confident that posh-git-sh isn't the culprit here.

A long shot. Do you think you need to update bash or Terminal itself?

Also, I think you may want to consider filing an Apple bug report.

**Comment by erikhuizinga** [comment]
I work on Terminal v2.7.1 (387), which is the latest stable release [according to Wikipedia at the moment of writing](https://en.wikipedia.org/w/index.php?title=Terminal_(macOS)&oldid=746929781). Also, I'm running Bash v4.4.5(1)-release (`echo $BASH_VERSION`), again, the latest stable version [according to Wikipedia](https://en.wikipedia.org/w/index.php?title=Bash_(Unix_shell)&oldid=754485030).

I'll contact Apple about the issue.

**Comment by erikhuizinga** [comment]
Thanks for taking the time to look into this! 👍 I hope I'll find a solution for this (and if so, I'll report back here).

**Comment by erikhuizinga** [comment]
I've opened a discussion thread [here](https://discussions.apple.com/thread/7786301).
