### ISSUE TITLE
Weird characters on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by stereokai** [lyze/posh-git-sh#20]
First of all, @lyze, huge thank you for porting this extension to bash! I've been using Powershell with Git on Windows for the better part of my career. Now I'm transitioning to Hyper with native Bash on Windows in Windows 10 - and I'm happy that I can continue using this excellent syntax.

I followed your instructions precisely:
![bashrc](https://cloud.githubusercontent.com/assets/2685357/21142965/4fe905ca-c14d-11e6-95be-77c2b40d0059.PNG)

And consequently the prompt is shown with the Git Posh syntax, on Hyper:
![hypertm](https://cloud.githubusercontent.com/assets/2685357/21142988/70534ece-c14d-11e6-929f-d9880ce2f574.PNG)
However, do you notice the `╔` in the start of the prompt line?

My goal is to use Hyper (terminal emulator) with the native Bash on Windows (which is Bash version 4.3). However, if I'm just loading Bash by itself, this is what I'm getting:
![bash on windows](https://cloud.githubusercontent.com/assets/2685357/21143098/f67ce4c4-c14d-11e6-8144-bbfc9db577c0.PNG)

As you can see the repo status is all messed up, but I don't mind because it displays correctly on Hyper. But can you see that `☺` character in the start of the prompt line?

**Comment by lyze** [comment]
I made a cursory search. Hyper seems to have some issues related to displaying Unicode:

* (Closed) https://github.com/zeit/hyper/issues/589
* (Open) https://github.com/zeit/hyper/issues/607

Can you see if any workarounds in those threads work for you?

As a fallback, you can always get rid of the status indicators in the code.

**Comment by lyze** [comment]
As for using native Windows 10 bash, I found this: http://superuser.com/questions/1108443/utf8-characters-in-windows-10-bash-terminal

**Comment by stereokai** [comment]
@lyze props for such a quick reply and an extensive research. What did you mean by this?
> As a fallback, you can always get rid of the status indicators in the code.

**Comment by stereokai** [comment]
I couldn't find a fix via those links, however, removing the `user@host` portion of the prompt also removed that hidden character. I don't require that kind of info so I'm happy :)

**Comment by lyze** [comment]
> What did you mean by this?
>> As a fallback, you can always get rid of the status indicators in the code.
You can also change the status symbol to your liking [around here](https://github.com/lyze/posh-git-sh/blob/4cf1067eee5ea952bb84d24d237616225ba30cc4/git-prompt.sh#L212).

You can also set `bash.enableStatusSymbol` your git configuration to be false (explained in the README).

**Comment by stereokai** [comment]
I don't have a problem with the status symbols, though. They are great :)

In fact, I did want to replace the $ symbol with something else, but couldn't make it work.

**Comment by lyze** [comment]
I meant that the status symbols are Unicode characters, and may have been part of your problem. It seems you found the root cause, though.
