### ISSUE TITLE
When will posh-git-sh retrieve git status automatically?

### ISSUE THREAD

**Issue by alexya** [lyze/posh-git-sh#26]
[https://stackoverflow.com/questions/44815493/git-checkout-to-another-branch-cannot-show-its-correct-status](url)

I met an issue related to git status, please see the thread in stackoverflow.com. 

I want to double check with you, will posh-git-sh script update the local repository status such as `git fetch` when I ran `git checkout master` to swtich branches? 

From the design of git, when running `git checkout <branch_name>` it will *not* fetch the information from remote repository. But one of my computer can get updated staus but another computer failed. I think it may be that I mis-config posh-git-sh in the computer. 

But I don't know where I made mistake. What I did these days is to make my script install oh-my-zsh and posh-git-sh automaticaly. [https://github.com/alexya/envconfig/blob/master/setup.sh](url)

Any help will be much appreciated.

**Comment by lyze** [comment]
The script does not perform a fetch, since that might be a time-consuming operation. The core of the script is an exercise in parsing the output of `git status`.

Do you suspect a bug? We would need more detailed steps to reproduce.

**Comment by alexya** [comment]
I created a repo 'Test-Git' to have a test. Yes, git can not know if the remote repository is updated. We need to run `git fetch` to update the status. 
But, I really have one computer which could auto-update the staus of a remote repository. Every time when I pressed `enter` in terminal, it can tell me the true status. 

It is not a posh-git-sh issue. I think we can close this thread.
