### ISSUE TITLE
Can posh-git-sh work for iterm2 terminal?

### ISSUE THREAD

**Issue by alexya** [lyze/posh-git-sh#27]
Before I used MacOSX default `terminal` tool. 
* I download the Solarized Dark theme for it
* install posh-git-sh by my scripts. e.g. https://github.com/alexya/envconfig 
And it can work well for a long time.

Today, I downloaded the tool `iterm2`.  But the `posh-git-sh` worked partly. (see the screenshot)
Any help will be much appreciated. thx.

![image](https://user-images.githubusercontent.com/2831220/28058768-51f289e8-6654-11e7-8465-c40cafe361e2.png)

**Comment by lyze** [comment]
I'm not sure I understand. The script seems to be working as intended by using the colors from the solarized theme.

**Comment by alexya** [comment]
Sorry for the confusion. From the screenshot, the left is default terminal of MacOSX. I set the username and computer color is 'green'. and the branch information of git is 'blue', the time information is 'purple'. All the colors are correct. 
The right is 'iTerm2' terminal. You can see the color is 'gray', not 'green' or 'blue'. 

All the settings for the 'terminal' and 'iterm2' are the same. Both are using Solarized Dark theme and zsh, oh-my-zsh, and posh-git-sh.

**Comment by lyze** [comment]
I don't know the specifics of configuring colors, but it sounds like there is inconsistent behavior between both terminal emulators. I suggest that you try to reduce the failure to a minimal case that doesn't work, since there are many complex interactions with the theme, color emulation, and environment variables.

**Comment by alexya** [comment]
Yes. It seems that the terminal's theme causes the zsh/oh-my-zsh fail to set the color set in zsh-theme.
e.g. I removed the terminal theme 'Solarized Dark theme' for both MacOSX default terminal app and iTerms app. Just use theirs default settings. The result is as the following. 
Left is MacOSX default terminal, and right is iTerm2.

![image](https://user-images.githubusercontent.com/2831220/28111009-a2530246-6726-11e7-84f1-fbdcbb6f2ea7.png)
