### ISSUE TITLE
ZSH

### ISSUE THREAD

**Issue by deniskril** [lyze/posh-git-sh#28]
Hello.
How can I add git status in .zshrc?

**Comment by lyze** [comment]
Based on [this link to the `precmd` function mentioned in the readme](http://zsh.sourceforge.net/Doc/Release/Functions.html#index-precmd), can you try something like the following:

```zsh
func precmd() {
  __posh_git_ps1 "\u@\h:\w " "\\\$ "
}
```
I can add this to the readme if this works and is simple enough.

**Comment by deniskril** [comment]
I have prompt:
`if [ $(id -u) -eq 0 ];
then

PROMPT=$'%{$fg[white]%}%D{%H:%M:%S} %{$fg[white]%}(%{$fg[green]%}%n%{$fg[red]%}@%{$fg[green]%}%M%{$fg[white]%})%{$reset_color%} \
%{$fg[cyan]%}%d/%{$fg[white]%}>%{$reset_color%}'

else

PROMPT=$'%{$fg[white]%}%D{%H:%M:%S} %{$fg[white]%}(%{$fg[green]%}%n%{$fg[white]%}@%{$fg[green]%}%M%{$fg[white]%})%{$reset_color%} \
%{$fg[cyan]%}%d/%{$fg[white]%}>%{$reset_color%}'

fi
`

How can I add git status? Please help!

**Comment by lyze** [comment]
Note that `__posh_git_ps1` sets `PS1`, which is why we create a `precmd` function in `.zshrc`. Can you modify the arguments to `__posh_git_ps1` appropriately in `precmd`? If you need more control you can try using `__posh_git_echo`, which only prints the status indicator.

**Comment by deniskril** [comment]
Thank You!
I have create 

`
func precmd() {
if [ $(id -u) -eq 0 ];

then

PS1=__posh_git_ps1 "%{$fg[white]%}%D{%H:%M:%S} %{$fg[white]%}(%{$fg[green]%}%n%{$fg[red]%}@%{$fg[green]%}%M%{$fg[white]%})%{$reset_color%}" "
%{$fg[cyan]%}%d/%{$fg[white]%}>%{$reset_color%}"

else

PS1=__posh_git_ps1 "%{$fg[white]%}%D{%H:%M:%S} %{$fg[white]%}(%{$fg[green]%}%n%{$fg[white]%}@%{$fg[green]%}%M%{$fg[white]%})%{$reset_color%}" "
%{$fg[cyan]%}%d/%{$fg[white]%}>%{$reset_color%}"

fi

}
`

**Comment by lyze** [comment]
Looks good. It seems like you don't need the assignment of `PS1` because `__posh_git_ps1` [already makes the assignment](https://github.com/lyze/posh-git-sh/blob/f90fcc9a8d4ec93f1ed3fa0196974f7ab4ef0140/git-prompt.sh#L123).
