### ISSUE TITLE
Consider Numeric Indicator of Commits Ahead/Behind

### ISSUE THREAD

**Issue by beufordy3k** [lyze/posh-git-sh#31]
One feature I like about posh-git is the numeric indicator of how many commits I am behind or ahead after doing a fetch.

Have you considered adding such? Would you entertain a pull request?

Example:

#### Powershell
```
C:\source\DataMigrator [develop ↓4]>
```

#### Ubuntu
```bash
myuser@host:~/source/DataMigrator [develop ↓]$
```

**Comment by lyze** [comment]
That sounds like a great idea, and it should be pretty straightforward to do.

Unfortunately I haven't been keeping very good track of new features in posh-git.
