### ISSUE TITLE
output='' error information will show in shell prompt

### ISSUE THREAD

**Issue by alexya** [lyze/posh-git-sh#32]
Hi, I got an error when using this script. 

please take a look at it. 
```
alexya@Alex-MacPro [08:52:19] [~/Source/Git/posh-git-sh] output=''
[output_error_info ?]
-> $ ls
README.md git-prompt.sh
```

after investigating, I think it may happen in git-prompt.sh
```
    # Find how many commits we are ahead/behind our upstream
    if [ -z "$legacy" ]; then
        local output
        output=$(git rev-list --count --left-right $upstream...HEAD 2>/dev/null)
        return_code=$?
        IFS=$' \t\n' read -r __POSH_BRANCH_BEHIND_BY __POSH_BRANCH_AHEAD_BY <<< $output
    else
        local output
        output=$(git rev-list --left-right $upstream...HEAD 2>/dev/null)
        return_code=$?
        # produce equivalent output to --count for older versions of git
        while IFS=$' \t\n' read -r commit; do
            case "$commit" in
            "<*") (( __POSH_BRANCH_BEHIND_BY++ )) ;;
            ">*") (( __POSH_BRANCH_AHEAD_BY++ ))  ;;
            esac
        done <<< $output
    fi
```

the line `local output` will print error information `output=''` in shell. (I don't know the reason)
The fix is to change to 
```
        local output=$(git rev-list --count --left-right $upstream...HEAD 2>/dev/null)
```

and then, the shell is good. e.g.
```
alexya@Alex-MacPro [08:56:56] [~/Source/Git/posh-git-sh] [output_error_info ≡]
-> $ ls
README.md git-prompt.sh
```

I don't have the permission to create a branch, so, could u please take a look at it? 

My macos version is 10.10.1
git version is 2.7.2
shell is oh-my-zsh

**Comment by Pfeif-Master** [comment]
I was able to fix the issue locally.

in function: **__posh_git_ps1_upstream_divergence**
on line: __507__ you are missing a "=" after declaring the variable __output__

```
-   local output
+   local output=
```

shells like _fish_ and _zsh_ force a new line so the next promt will be on its own line. without the "=" the script prints a blank with no "\n" trigguring the cell to add output.

in bash this blank is invisable
