### ISSUE TITLE
zsh instructions don't appear to work in macOS Catalina

### ISSUE THREAD

**Issue by ajyong** [lyze/posh-git-sh#43]
Before we begin, I'm no expert with `zsh` (or any heavy shell customizations really), but since macOS Catalina made it the default shell on me, I figured I would just live with it.  I'm also using plain-old Terminal.app, not iTerm2 or anything else.

I followed the instructions in the README, which at the time said to define `precmd` as follows:

```zsh
precmd() {
  __posh_git_ps1 '\u@\h:\w ' '$ '
}
```

I pasted that into my `.zshrc` file and reloaded my terminal.  However, this is what happened:
![image](https://user-images.githubusercontent.com/6334517/75910671-7a6f7f00-5e0b-11ea-8772-aa1427f4a38f.png)
`posh-git-sh` worked, but prompt expansion wasn't.  It took a bit of digging online before I found [this comment](https://stackoverflow.com/questions/59122240/ps1-env-cannot-parse-on-the-new-mac-catalina#comment104474441_59122240) on StackOverflow, showing that `zsh` prompt expansions are totally different from `bash`, which I'm guessing uses backslashes.  Here's what worked for me:

```zsh
precmd() {
  __posh_git_ps1 '%n@%m:%~ ' '$ '
}
```
![image](https://user-images.githubusercontent.com/6334517/75911036-22854800-5e0c-11ea-98c6-ea93eee20cbc.png)
I can submit a quick PR if it turns out the instructions need to be changed for `zsh` users.  Thanks!

**Comment by lyze** [comment]
Indeed, prompt sequence expansion is different. A pull request would be nice if you have the time.

http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html

**Comment by ajyong** [comment]
I'll close this, thanks @mrsheepuk for submitting the PR!
