### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [lyze/posh-git-sh#55]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by lyze** [comment]
Hi! This is done now. Is this sufficient?

**Comment by unixorn** [comment]
Perfect, thanks!
