### ISSUE TITLE
Using default prompt kills standard terminal colors

### ISSUE THREAD

**Issue by OldManBrodie** [lyze/posh-git-sh#64]
Following the directions to install posh-git-sh, I have `export PROMPT_COMMAND='__posh_git_ps1 "\u@\h:\w " "\\\$ ";'$PROMPT_COMMAND` in my .bashrc file, which should just append the git-related stuff at the end of my prompt. It does accomplish this, but it also seems to reset my colors in the prompt (ie: the username/host and path portions).

See here:
![2024-12-30_11-50](https://github.com/user-attachments/assets/2e325663-63bc-46e5-a0fd-c8052c1bcb99)

**Comment by lyze** [comment]
Your colors in the username/host portions are likely set somewhere in your `.bashrc`, which may source other files. The `PROMPT_COMMAND` that you showed doesn't have any colors.

```shell
export PROMPT_COMMAND='__posh_git_ps1 "\u@\h:\w " "\\\$ ";'$PROMPT_COMMAND
```

If you'd like blue as shown above, you can try something like this:[^1][^2]

```shell
export PROMPT_COMMAND=`__posh_git_ps1 "\[\e[0;34m\]\u@\h:\w " "\\\$ ";'$PROMPT_COMMAND
```

[^1]: https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html
[^2]: https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html

**Comment by OldManBrodie** [comment]
Yeah, I feel silly now. Thanks for pointing out how to do that.
