### ISSUE TITLE
Stash status symbol

### ISSUE THREAD

**Issue by spooky** [lyze/posh-git-sh#8]
Currently the symbol used to show if there's anything in stash is a '$' - that's also the default ending character for most default prompt setups. As a result there's a doubled '$' character when there's something in stash.
It would be great to change that to something else (a '*' maybe?) and even better to have this parametrized.

**Comment by lyze** [comment]
I just refactored out the stash indicator symbol in dacc48212e81f6da0eaf6912718bdcc39eecfce3.

I don't feel that strongly about changing it. It would be a little overkill to have it parameterized through the environment or through a git config file, so I'll just point you to [line 167 of dacc482](https://github.com/lyze/posh-git-sh/blob/dacc48212e81f6da0eaf6912718bdcc39eecfce3/git-prompt.sh#L167). Just change that from `'$'` to whatever you want.

Does this work for you?

**Comment by spooky** [comment]
Yeap, I actually changed it in the reported version so sfo my personal usage - everything is fine. Just reported as an improvement potential
