### ISSUE TITLE
__git_ps1 already defined

### ISSUE THREAD

**Issue by ardentsword** [lyze/posh-git-sh#9]
I had a problem where __git_ps1 would always output (branche_name), even though I included your file. This is fixed if I change the name of __git_ps1 to something like __git_ps1_new.
I don't know how or where, but something was rewriting the function call.

(now that I got it working it's a lovely piece of work, you deserve more recognition for this!)

**Comment by lyze** [comment]
It seems like you're describing the behavior of the [standard git prompt script](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh). Perhaps the "usual" git prompt was sourced somewhere on startup in your shell?

**Comment by ardentsword** [comment]
That is probably the case, but I have not included it manually ( as can be seen [here](https://github.com/ardentsword/dotfiles) ). So this probably is some default behavior from the latest git version? I couldn't find any documentation about this feature, so this is pretty strange.

**Comment by lyze** [comment]
Have you checked the [usual suspects](http://www.linuxfromscratch.org/blfs/view/svn/postlfs/profile.html) like /etc/profile, /etc/profile.d/, /etc/bashrc etc.?

**Comment by lyze** [comment]
I namespaced everything in 3017d66 to not collide with the actual git-prompt script, so hopefully similar things won't happen again.
